language: node_js
node_js:
  - "v9.11.2"
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/sudoku_test

after_success: npm run coverage

before_script:
  - psql -c 'create database sudoku_test' -U postgres
  - psql -U postgres -d sudoku_test -a -f table.sql
